apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "main.fullname" . }}
  labels:
    app: {{ include "main.fullname" . }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ include "main.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "main.fullname" . }}
    spec:
      initContainers:
        - name: wait-for-database
          image: postgres:17.5
          command: ["sh", "-c", "until pg_isready -h sample-nodejs-service-postgresql -p 5432; do echo 'waiting for database to be ready'; sleep 2; done"]
      containers:
        - name: {{ include "main.name" . }}
          image: "dmi3papka/sample-nodejs-service:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "80"
            - name: DB_HOST
              value: sample-nodejs-service-postgresql
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password
            - name: DB_DATABASE
              value: app
          livenessProbe:
            httpGet:
              port: {{ .Values.probe.port }}
              path: {{ .Values.probe.path }}
            initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probe.timeoutSeconds }}
            failureThreshold: {{ .Values.probe.failureThreshold }}
            periodSeconds: {{ .Values.probe.periodSeconds }}
          readinessProbe:
            httpGet:
              port: {{ .Values.probe.port }}
              path: {{ .Values.probe.path }}
            initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probe.timeoutSeconds }}
            failureThreshold: {{ .Values.probe.failureThreshold }}
            periodSeconds: {{ .Values.probe.periodSeconds }}
