apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "main.fullname" . }}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "main.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
