apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-nodejs-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sample-nodejs-service
                port:
                  number: 80