apiVersion: v1
kind: Service
metadata:
  name: sample-nodejs-service
spec:
  type: ClusterIP
  selector:
    app: sample-nodejs-service
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http