apiVersion: v1
kind: Service
metadata:
  name: sample-nodejs-service
spec:
  type: LoadBalancer
  selector:
    app: sample-nodejs-service-deployment
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
      name: http