apiVersion: v2
name: main
description: Sample NodeJS service
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 16.7.2
